### ISSUE TITLE
Problem with metadata icecast 

### ISSUE THREAD

**Issue by xzsaimon16** [joeyboli/html5-shoutcast-icecast-zeno-player#2]
Hi, I have a problem. The metadata with the icecast does not work for me, I don't know if you can help me

**Comment by joeyboli** [comment]
> Hi, I have a problem. The metadata with the icecast does not work for me, I don't know if you can help me

can you share your player ? so that I check and see where the issue is.

also make sure you have downloaded the latest version.

**Comment by xzsaimon16** [comment]
[prueba.zip](https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/files/11804667/prueba.zip)

**Comment by joeyboli** [comment]
Share URL to the player instead.

**Comment by xzsaimon16** [comment]
I don't have it hosted in url, only in the file that I send. there is the streaming url and the link for the json file

**Comment by joeyboli** [comment]
just checked the code and you have the old version. please re-download the code from github, I made fixes to work with any URL last two days.

**Comment by xzsaimon16** [comment]
![Sin título](https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/assets/103347815/580393e5-d7b4-4e60-b41b-2ce5ef0a4999)

ok, I tried it and at the beginning the metadata with my url and jason worked, after editing the images and the name of my station it stopped working. Now the original wue player that you have shared does not work. In the attached image you can see the error

**Comment by xzsaimon16** [comment]
![IMG_20230620_223455](https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/assets/103347815/19ff76d2-2737-48df-95ff-c5e84ea5ec72)

From what I see it works sometimes yes and sometimes no

**Comment by joeyboli** [comment]
okay, send me your stream URL

**Comment by xzsaimon16** [comment]
stream : https://acp2.lorini.net:19030/stream



json:  https://acp2.lorini.net:8080/json/stream/ritmo-digital

**Comment by joeyboli** [comment]
okay so I noticed my API server was not picking the stream metadata, will check the cause of It and let you know.

**Comment by xzsaimon16** [comment]
Thanks

**Comment by joeyboli** [comment]
seems to be working now, I dont quite get why it was not working though, any other stream URL I pass works fine so I am a bit confused.

**Comment by joeyboli** [comment]
here is the API endpoint that I use for the app [https://api.streamafrica.net/metadata/index.php?z=https://acp2.lorini.net:19030/stream](url)

**Comment by xzsaimon16** [comment]
yes, it worked for a few minutes then it stopped working

**Comment by xzsaimon16** [comment]
it does not work

**Comment by joeyboli** [comment]
Yeah unfortunately, what control panel do you use ?

Sent from my T-Mobile 4G LTE Device
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xzsaimon16** [comment]
![Screenshot_2023-06-21-17-55-38-804_com android chrome](https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/assets/103347815/b5d8395d-4c00-464e-ae50-94aa80f13fb3)

I don't know. I contracted a service which I don't know which panel it uses. here I attach a screenshot

**Comment by joeyboli** [comment]
I have seen it uses a media CP panel, so I will write a custom code to parse your json and then pass the metadata to the player.

**Comment by joeyboli** [comment]
open line 378 and replace ''https://api.streamafrica.net/metadata/index.php?z='+URL_STREAMING'

with 

'https://api.streamafrica.net/metadata/mediacp.php?url=https://acp2.lorini.net:8080/json/stream/ritmo-digital'

**Comment by xzsaimon16** [comment]
![IMG_20230621_200911](https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/assets/103347815/d6b9c826-1c3e-490e-913b-3edbe588b54e)
![IMG_20230621_200848](https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/assets/103347815/51121025-8ec1-4aeb-b76c-46d51d7c7ba1)

now it works perfectly. One detail, I have noticed that in some songs the name does not show well. I reviewed the songs and they are well written. for what is this? thanks for the help friend

**Comment by joeyboli** [comment]
sorry but that depends on the type of characters been sent.
