### ISSUE TITLE
Problem with Api 

### ISSUE THREAD

**Issue by xzsaimon16** [joeyboli/html5-shoutcast-icecast-zeno-player#4]
Hi, I've been using the producer and it just shows me that the API doesn't work... I attached the image
![Screenshot_2023-07-21-08-04-11-739_com android chrome](https://github.com/joeyboli/html5-shoutcast-icecast-zeno-player/assets/103347815/34a7c5d8-5a6c-4ea8-bcf6-87d21f8b7e47)

**Comment by joeyboli** [comment]
Sorry, API is now behind a paywall, there are many people reselling this player with the api and it costs a lot to keep it running.

**Comment by xzsaimon16** [comment]
I understand. Some alternative?

**Comment by joeyboli** [comment]
what type of URL do you use ?

**Comment by xzsaimon16** [comment]
http.

I have luna player and it works, any way to extract the api from there?

**Comment by joeyboli** [comment]
Luna Player extracts Song info from stream provider's API instead of parsing the stream URL.

**Comment by xzsaimon16** [comment]
Ok, any way to get it working again?

**Comment by joeyboli** [comment]
only way to get it working is by paying for API costs 5 $ every three months.

you can check them at https://joeycast.com/jcplayer

**Comment by xzsaimon16** [comment]
It has a bad payment method, it doesn't work for me. The currency is unknown to me

**Comment by joeyboli** [comment]
> It has a bad payment method, it doesn't work for me. The currency is unknown to me

1 USD = 11.67 GHS.

5 USD = 58.37 GHS.

if you pay it will automatically convert in your currency.
